### ISSUE TITLE
TODO for 5.4.12

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#942]
- [x] Enable hardware acceleration in electron, disable with flag only.
- [x] Make text in pricing mode white instead of black for benefits.
- [x] Add gathering type icon inside reducedBy popup.
- [x] Fix issue with item amount not taken into account when adding to list in item page.
- [x] Fix wrong orange theme name.
- [ ] ~~Fix spawn window issue (thundergut, May 28th, 16:30 UTC).~~ Not enough data, seems related to 00h and weather stuff
- [x] Add ability to add item to a list from item page even if not craftable.
